### ISSUE TITLE
你好，我们现在的效果根你的不太一样，应该改哪里呢

### ISSUE THREAD

**Issue by liguangze** [kntryer/LineChart#2]
我们的效果现在那个点是空心点，并且根线有一定的dp，这个地方应该改哪里呢，我试了半天还是不好实现，还有下面的阴影部分是渐变的阴影效果，可以实现吗，求提供下思路，感谢开源

**Comment by kntryer** [comment]
不好意思，现在才注意有个 issue ，你要的效果已经更新到 1.2 版本了，代码写了注释
